#!/sbin/openrc-run

mssql_command=/opt/mssql/bin/sqlservr

depend() {
	use net.lo
	need localmount
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet \
		--exec "${mssql_command}" \
		--pidfile "/var/run/mssql.pid" \
		--background \
		-u mssql -g mssql \
		--
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --exec "${mssql_command}" \
		--pidfile "/var/run/mssql.pid"
	eend $?
}
